version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3020:3020"
    volumes:
      - ./server:/app
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3005:3005"
    volumes:
      - ./client:/app
      - frontend_node_modules:/app/node_modules  # ✅ fix ici
    working_dir: /app
    command: sh -c "npm install && npm run dev"  # 🛠️ assure que tout est installé

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  frontend_node_modules:  # ✅ volume nommé ici
